---
- name: Install and configure packages on Alpine Linux
  hosts: all
  become: true

# Alpine packages are available at https://pkgs.alpinelinux.org/packages
  tasks:
    - name: Install the GNU Bourne Again shell
      apk:
        name: bash
        state: present
        update_cache: yes

    - name: Install super user do
      apk:
        name: sudo
        state: present
        update_cache: yes

    - name: Install client url
      apk:
        name: curl
        state: present
        update_cache: yes        

    - name: Install common CA certificates PEM files from Mozilla
      apk:
        name: ca-certificates
        state: present
        update_cache: yes   

    - name: Install network utility to retrieve files from the Web
      apk:
        name: wget
        state: present
        update_cache: yes   

    - name: Install dotnet runtime
      apk:
        name: aspnetcore-runtime-7.0
        state: present
        update_cache: yes

    - name: Install Nginx web server
      apk:
        name: nginx
        state: present
        update_cache: yes
