name: Greet Everyone
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Greeting Action
      uses: ./.github/actions/action-test32
